#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_gpio.h>
#include <furi_hal_serial.h>
#include <furi_hal_serial_control.h>

#include <gui/gui.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_input.h>
#include <gui/view_dispatcher.h>
#include <gui/view_port.h>
#include <input/input.h>
#include <notification/notification.h>
#include <notification/notification_messages.h>
#include <power/power_service/power.h>
#include <storage/storage.h>

#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>

/* generated by fbt from .png files in images folder */
#include <uhf_expansion_icons.h>

#define TAG "uhf_expansion"

#define UHF_BAUD_RATE_LOW     9600U
#define UHF_BAUD_RATE_HIGH    115200U
#define UHF_FRAME_START       0xA0U
#define UHF_DEFAULT_ADDR      0x00U
#define UHF_CMD_GET_VERSION   0x72U
#define UHF_CMD_START_INV     0x89U
#define UHF_CMD_STOP_INV      0x8CU
#define UHF_CMD_INV_ALT       0x8AU
#define UHF_PAYLOAD_START_INV 0x01U
#define UHF_PROBE_TIMEOUT_MS  240U

#define UHF_SOFT_UART_BIT_US         104U
#define UHF_SOFT_UART_IDLE_POLL_US   10U
#define UHF_SOFT_UART_FRAME_WAIT_US  120U
#define UHF_SOFT_UART_PROBE_WINDOWMS 380U
#define UHF_SOFT_UART_RX_BATCH       1U
#define UHF_INV_CMD_COOLDOWN_MS      450U
#define UHF_LIST_VISIBLE_ROWS        5U
#define UHF_ABOUT_VISIBLE_LINES      5U

#define UHF_TARGET_TX_PIN_FALLBACK 6
#define UHF_TARGET_RX_PIN_FALLBACK 4
#define UHF_BRIDGE_TX_EXT_PIN      13
#define UHF_BRIDGE_RX_EXT_PIN      14

#define UHF_MAX_TAGS          120U
#define UHF_EPC_HEX_MAX       64U
#define UHF_RX_STREAM_SIZE    1024U
#define UHF_FRAME_BUFFER_SIZE 1024U
#define UHF_RX_CHUNKS_PER_PASS 4U
#define UHF_RX_FRAMES_PER_PASS 24U
#define UHF_DIAG_LOG_LINES    48U
#define UHF_DIAG_LOG_LEN      96U

#define UHF_APP_DATA_DIR APP_DATA_PATH("uhf_expansion")
#define UHF_DIAG_DATA_DIR "/int/uhf_expansion"

typedef struct {
    InputEvent input;
} UhfEvent;

typedef struct {
    ViewDispatcher* dispatcher;
    bool submitted;
} UhfFilenameInputCtx;

typedef struct {
    ViewDispatcher* dispatcher;
    uint32_t selected;
    bool submitted;
} UhfListMenuCtx;

typedef enum {
    UhfListMenuItemSave = 0,
    UhfListMenuItemAbout = 1,
} UhfListMenuItem;

typedef enum {
    UhfPageCounter = 0,
    UhfPageList = 1,
    UhfPageAbout = 2,
} UhfPage;

typedef struct {
    bool used;
    char epc[UHF_EPC_HEX_MAX + 1];
    uint16_t read_count;
    uint32_t last_seen;
    uint32_t rssi;
    uint32_t frequency;
    uint8_t antenna;
} UhfTagEntry;

typedef struct {
    Gui* gui;
    ViewPort* view_port;
    NotificationApp* notifications;
    FuriMessageQueue* event_queue;
    FuriStreamBuffer* rx_stream;
    FuriMutex* data_mutex;
    Power* power;

    FuriHalSerialHandle* serial;
    FuriHalSerialId serial_id;
    int8_t tx_ext_pin;
    int8_t rx_ext_pin;
    uint32_t baud_rate;
    bool otg_was_enabled;
    bool otg_enabled_by_app;

    uint8_t frame_buffer[UHF_FRAME_BUFFER_SIZE];
    size_t frame_buffer_len;

    UhfTagEntry tags[UHF_MAX_TAGS];
    size_t tag_count;

    bool inventory_running;
    bool exit_requested;
    bool hardware_ready;
    bool soft_uart_enabled;
    const GpioPin* soft_tx_gpio;
    const GpioPin* soft_rx_gpio;
    uint32_t rx_bytes;
    uint32_t rx_frames;
    uint32_t rx_errors;
    uint32_t key_count;
    char last_rx_hex[41];
    char diag_log[UHF_DIAG_LOG_LINES][UHF_DIAG_LOG_LEN];
    uint8_t diag_head;
    uint8_t diag_count;
    bool diag_save_pending;
    bool diag_save_running;
    bool down_long_latched;
    uint32_t last_inv_cmd_tick;
    uint32_t last_tag_beep_tick;
    UhfPage page;
    UhfPage about_return_page;
    size_t list_top_index;
    size_t list_selected_index;
    size_t about_top_line;

    char status[64];
    char version[24];
    char csv_filename[32];
    bool startup_active;
    char startup_text[32];
    char startup_subtext[40];
    uint8_t startup_dots;
    uint32_t last_redraw_tick;
} UhfApp;

typedef struct {
    char epc[UHF_EPC_HEX_MAX + 1];
    uint16_t count;
} UhfTagPreview;

static void uhf_format_list_epc_compact(
    Canvas* canvas,
    const char* epc,
    int max_width,
    char* out,
    size_t out_size) {
    if(!canvas || !out || out_size == 0U) return;

    out[0] = '\0';
    if(!epc) return;
    if(max_width <= 0) return;

    strncpy(out, epc, out_size - 1U);
    out[out_size - 1U] = '\0';
    if(canvas_string_width(canvas, out) <= max_width) {
        return;
    }

    const size_t epc_len = strlen(epc);
    if(epc_len <= 8U) {
        return;
    }

    const char* dots = "......";
    size_t prefix_len = epc_len / 2U;
    size_t suffix_len = epc_len - prefix_len;
    if(prefix_len > 12U) prefix_len = 12U;
    if(suffix_len > 12U) suffix_len = 12U;

    if(prefix_len < 4U) prefix_len = 4U;
    if(suffix_len < 4U) suffix_len = 4U;

    while(prefix_len + suffix_len > epc_len) {
        if(prefix_len > suffix_len) {
            prefix_len--;
        } else {
            suffix_len--;
        }
    }

    snprintf(
        out,
        out_size,
        "%.*s%s%.*s",
        (int)prefix_len,
        epc,
        dots,
        (int)suffix_len,
        epc + (epc_len - suffix_len));

    while(canvas_string_width(canvas, out) > max_width && (prefix_len > 4U || suffix_len > 4U)) {
        if(prefix_len >= suffix_len && prefix_len > 4U) {
            prefix_len--;
        } else if(suffix_len > 4U) {
            suffix_len--;
        } else {
            break;
        }

        snprintf(
            out,
            out_size,
            "%.*s%s%.*s",
            (int)prefix_len,
            epc,
            dots,
            (int)suffix_len,
            epc + (epc_len - suffix_len));
    }

    while(prefix_len + suffix_len < epc_len) {
        size_t next_prefix = prefix_len;
        size_t next_suffix = suffix_len;

        if(next_prefix <= next_suffix && next_prefix < 12U && (next_prefix + next_suffix) < epc_len) {
            next_prefix++;
        } else if(next_suffix < 12U && (next_prefix + next_suffix) < epc_len) {
            next_suffix++;
        } else {
            break;
        }

        char candidate[40];
        snprintf(
            candidate,
            sizeof(candidate),
            "%.*s%s%.*s",
            (int)next_prefix,
            epc,
            dots,
            (int)next_suffix,
            epc + (epc_len - next_suffix));

        if(canvas_string_width(canvas, candidate) > max_width) {
            break;
        }

        prefix_len = next_prefix;
        suffix_len = next_suffix;
        strncpy(out, candidate, out_size - 1U);
        out[out_size - 1U] = '\0';
    }
}

static void uhf_on_rx_irq(FuriHalSerialHandle* handle, FuriHalSerialRxEvent event, void* context);
static void uhf_app_free(UhfApp* app);
static bool __attribute__((unused)) uhf_probe_reader_startup(UhfApp* app);
static void uhf_clear_tags(UhfApp* app);
static void uhf_process_rx(UhfApp* app);
static bool uhf_wait_for_version(UhfApp* app, uint32_t timeout_ms);
static bool uhf_has_version(UhfApp* app);
static void uhf_request_version(UhfApp* app);
static bool uhf_probe_current_serial(UhfApp* app, uint32_t baud);
static void uhf_start_inventory(UhfApp* app);
static void uhf_stop_inventory(UhfApp* app);
static bool uhf_open_serial(UhfApp* app, FuriHalSerialId serial_id);
static void uhf_close_serial(UhfApp* app);
static bool uhf_open_bridge_uart(UhfApp* app);
static void uhf_set_startup_text(UhfApp* app, const char* text, const char* subtext, uint8_t dots);

static const char* const uhf_about_lines[] = {
    "Features:",
    "- Fast inventory scan",
    "- Paged EPC list",
    "- Save CSV records",
    "",
    "Url:",
    "github.com/mtoolstec/",
    "fz-uhf-expansion",
};

static void uhf_draw_right_text(Canvas* canvas, int y, const char* text) {
    if(!canvas || !text) return;

    const int width = canvas_string_width(canvas, text);
    int x = 128 - width;
    if(x < 0) x = 0;
    canvas_draw_str(canvas, x, y, text);
}

static void uhf_draw_scan_state_icon(Canvas* canvas, int x, int y, bool running) {
    if(!canvas) return;

    if(running) {
        // Pause icon
        canvas_draw_box(canvas, x, y, 2, 7);
        canvas_draw_box(canvas, x + 4, y, 2, 7);
    } else {
        // Play icon
        canvas_draw_line(canvas, x, y, x, y + 6);
        canvas_draw_line(canvas, x, y, x + 5, y + 3);
        canvas_draw_line(canvas, x, y + 6, x + 5, y + 3);
    }
}

static void uhf_draw_scan_hint(Canvas* canvas, bool running) {
    if(!canvas) return;

    canvas_set_font(canvas, FontSecondary);
    const char* ok_text = "OK";
    const char* action_text = "Scan";
    const int ok_width = canvas_string_width(canvas, ok_text);
    const int action_width = canvas_string_width(canvas, action_text);
    const int icon_width = 6;
    const int gap_before_icon = 3;
    const int gap_after_icon = 4;
    const int total_width = ok_width + gap_before_icon + icon_width + gap_after_icon + action_width;

    int start_x = (128 - total_width) / 2;
    if(start_x < 0) start_x = 0;

    canvas_draw_str(canvas, start_x, 63, ok_text);

    const int icon_x = start_x + ok_width + gap_before_icon;
    const int icon_y = 56;
    uhf_draw_scan_state_icon(canvas, icon_x, icon_y, running);
    canvas_draw_str(canvas, icon_x + icon_width + gap_after_icon, 63, action_text);
}

static const NotificationSequence uhf_sequence_tag_found = {
    &message_force_speaker_volume_setting_1f,
    &message_note_c6,
    &message_delay_10,
    &message_sound_off,
    &message_delay_10,
    &message_note_c6,
    &message_delay_10,
    &message_sound_off,
    &message_delay_10,
    &message_note_c6,
    &message_delay_10,
    &message_sound_off,
    NULL,
};

static void uhf_diag_log(UhfApp* app, const char* fmt, ...) {
    if(!app) return;

    char line[UHF_DIAG_LOG_LEN];
    va_list args;
    va_start(args, fmt);
    vsnprintf(line, sizeof(line), fmt, args);
    va_end(args);

    const uint8_t idx = app->diag_head;
    strncpy(app->diag_log[idx], line, UHF_DIAG_LOG_LEN - 1U);
    app->diag_log[idx][UHF_DIAG_LOG_LEN - 1U] = '\0';

    app->diag_head = (uint8_t)((idx + 1U) % UHF_DIAG_LOG_LINES);
    if(app->diag_count < UHF_DIAG_LOG_LINES) {
        app->diag_count++;
    }
}

static int8_t __attribute__((unused))
    uhf_resolve_ext_pin_number(const char* pin_name_a, const char* pin_name_b, int8_t fallback) {
    const GpioPinRecord* pin = furi_hal_resources_pin_by_name(pin_name_a);
    if(!pin && pin_name_b) {
        pin = furi_hal_resources_pin_by_name(pin_name_b);
    }
    return pin ? (int8_t)pin->number : fallback;
}

static int8_t __attribute__((unused)) uhf_target_pin_a6(void) {
    static int8_t cached = INT8_MIN;
    if(cached == INT8_MIN) {
        cached = uhf_resolve_ext_pin_number("PA6", "A6", UHF_TARGET_TX_PIN_FALLBACK);
    }
    return cached;
}

static int8_t __attribute__((unused)) uhf_target_pin_a4(void) {
    static int8_t cached = INT8_MIN;
    if(cached == INT8_MIN) {
        cached = uhf_resolve_ext_pin_number("PA4", "A4", UHF_TARGET_RX_PIN_FALLBACK);
    }
    return cached;
}

static void uhf_format_pin_label(int8_t ext_pin, char* out, size_t out_size) {
    if(ext_pin < 0) {
        snprintf(out, out_size, "N/A");
        return;
    }

    const GpioPinRecord* pin = furi_hal_resources_pin_by_number((uint8_t)ext_pin);
    if(pin && pin->name) {
        snprintf(out, out_size, "%s", pin->name);
    } else {
        snprintf(out, out_size, "P%d", ext_pin);
    }
}

static void uhf_soft_uart_set_line(const GpioPin* gpio, bool high) {
    furi_hal_gpio_write(gpio, high);
}

static void uhf_soft_uart_tx_byte(UhfApp* app, uint8_t value) {
    if(!app->soft_uart_enabled || !app->soft_tx_gpio) return;

    // 8N1, LSB first, idle high.
    uhf_soft_uart_set_line(app->soft_tx_gpio, false);
    furi_delay_us(UHF_SOFT_UART_BIT_US);

    for(size_t i = 0; i < 8; i++) {
        uhf_soft_uart_set_line(app->soft_tx_gpio, (value >> i) & 0x01);
        furi_delay_us(UHF_SOFT_UART_BIT_US);
    }

    uhf_soft_uart_set_line(app->soft_tx_gpio, true);
    furi_delay_us(UHF_SOFT_UART_BIT_US);
}

static void uhf_soft_uart_tx(UhfApp* app, const uint8_t* data, size_t length) {
    for(size_t i = 0; i < length; i++) {
        uhf_soft_uart_tx_byte(app, data[i]);
    }
}

static bool uhf_soft_uart_rx_byte(UhfApp* app, uint8_t* out, uint32_t timeout_us) {
    if(!app->soft_uart_enabled || !app->soft_rx_gpio) return false;

    uint32_t waited = 0;
    while(true) {
        if(!furi_hal_gpio_read(app->soft_rx_gpio)) {
            // Confirm start bit in its middle.
            furi_delay_us(UHF_SOFT_UART_BIT_US / 2U);
            if(!furi_hal_gpio_read(app->soft_rx_gpio)) {
                uint8_t value = 0;
                furi_delay_us(UHF_SOFT_UART_BIT_US);
                for(size_t i = 0; i < 8; i++) {
                    if(furi_hal_gpio_read(app->soft_rx_gpio)) {
                        value |= (uint8_t)(1U << i);
                    }
                    furi_delay_us(UHF_SOFT_UART_BIT_US);
                }

                // Stop bit time.
                furi_delay_us(UHF_SOFT_UART_BIT_US / 2U);
                *out = value;
                return true;
            }
        }

        if(waited >= timeout_us) {
            return false;
        }

        furi_delay_us(UHF_SOFT_UART_IDLE_POLL_US);
        waited += UHF_SOFT_UART_IDLE_POLL_US;
    }
}

static void __attribute__((unused))
    uhf_soft_uart_configure(UhfApp* app, const GpioPin* tx_gpio, const GpioPin* rx_gpio) {
    furi_hal_gpio_init(tx_gpio, GpioModeOutputPushPull, GpioPullNo, GpioSpeedVeryHigh);
    furi_hal_gpio_write(tx_gpio, true);
    furi_hal_gpio_init(rx_gpio, GpioModeInput, GpioPullUp, GpioSpeedVeryHigh);

    app->soft_uart_enabled = true;
    app->soft_tx_gpio = tx_gpio;
    app->soft_rx_gpio = rx_gpio;
    app->serial = NULL;
}

static void uhf_force_direct_a6_a4(UhfApp* app) {
    if(!app) return;

    // Bridge wiring mode: use hardware UART lines on ext 13/14 for stable real-time RX.
    if(app->serial) {
        uhf_close_serial(app);
    }

    app->soft_uart_enabled = false;
    app->soft_tx_gpio = NULL;
    app->soft_rx_gpio = NULL;

    if(!uhf_open_bridge_uart(app)) {
        app->tx_ext_pin = -1;
        app->rx_ext_pin = -1;
        return;
    }

    app->baud_rate = UHF_BAUD_RATE_LOW;
    furi_hal_serial_set_br(app->serial, app->baud_rate);

    app->frame_buffer_len = 0;
    app->last_rx_hex[0] = '\0';
    if(app->rx_stream) {
        (void)furi_stream_buffer_reset(app->rx_stream);
    }

    uhf_diag_log(app, "Bridge UART TX:%d RX:%d", app->tx_ext_pin, app->rx_ext_pin);
}

static bool uhf_data_lock(UhfApp* app, uint32_t timeout) {
    if(!app->data_mutex) return false;
    return furi_mutex_acquire(app->data_mutex, timeout) == FuriStatusOk;
}

static void uhf_data_unlock(UhfApp* app) {
    if(app->data_mutex) {
        furi_mutex_release(app->data_mutex);
    }
}

static void uhf_set_status(UhfApp* app, const char* fmt, ...) {
    char buffer[sizeof(app->status)];

    va_list args;
    va_start(args, fmt);
    vsnprintf(buffer, sizeof(buffer), fmt, args);
    va_end(args);

    if(uhf_data_lock(app, 10)) {
        strncpy(app->status, buffer, sizeof(app->status) - 1);
        app->status[sizeof(app->status) - 1] = '\0';
        uhf_data_unlock(app);
    } else {
        strncpy(app->status, buffer, sizeof(app->status) - 1);
        app->status[sizeof(app->status) - 1] = '\0';
    }
}

static void uhf_notify_tag_found(UhfApp* app) {
    if(!app || !app->notifications) return;

    app->last_tag_beep_tick = furi_get_tick();
    notification_message(app->notifications, &uhf_sequence_tag_found);
}

static void uhf_filename_input_done(void* context) {
    UhfFilenameInputCtx* ctx = context;
    if(!ctx) return;

    ctx->submitted = true;
    if(ctx->dispatcher) {
        view_dispatcher_stop(ctx->dispatcher);
    }
}

static bool uhf_filename_input_back(void* context) {
    UhfFilenameInputCtx* ctx = context;
    if(!ctx) return true;

    if(ctx->dispatcher) {
        view_dispatcher_stop(ctx->dispatcher);
    }
    return true;
}

static void uhf_sanitize_filename(const char* input, char* out, size_t out_size) {
    if(!out || out_size == 0) return;

    size_t j = 0;
    if(input) {
        for(size_t i = 0; input[i] && j + 1 < out_size; i++) {
            const unsigned char c = (unsigned char)input[i];
            if(isalnum(c) || c == '_' || c == '-') {
                out[j++] = (char)c;
            }
        }
    }

    if(j == 0) {
        strncpy(out, "tags", out_size - 1);
        out[out_size - 1] = '\0';
    } else {
        out[j] = '\0';
    }
}

static bool uhf_prompt_csv_filename(UhfApp* app, char* out, size_t out_size) {
    if(!app || !app->gui || !app->view_port || !out || out_size < 2) return false;

    strncpy(out, "tags", out_size - 1);
    out[out_size - 1] = '\0';

    TextInput* text_input = text_input_alloc();
    ViewDispatcher* dispatcher = view_dispatcher_alloc();
    if(!text_input || !dispatcher) {
        if(text_input) text_input_free(text_input);
        if(dispatcher) view_dispatcher_free(dispatcher);
        return false;
    }

    UhfFilenameInputCtx ctx = {
        .dispatcher = dispatcher,
        .submitted = false,
    };

    text_input_set_header_text(text_input, "CSV file name");
    text_input_set_minimum_length(text_input, 1);
    text_input_set_result_callback(text_input, uhf_filename_input_done, &ctx, out, out_size, false);

    view_dispatcher_set_event_callback_context(dispatcher, &ctx);
    view_dispatcher_set_navigation_event_callback(dispatcher, uhf_filename_input_back);
    view_dispatcher_add_view(dispatcher, 0, text_input_get_view(text_input));

    gui_remove_view_port(app->gui, app->view_port);
    view_dispatcher_attach_to_gui(dispatcher, app->gui, ViewDispatcherTypeFullscreen);
    view_dispatcher_switch_to_view(dispatcher, 0);
    view_dispatcher_run(dispatcher);

    view_dispatcher_remove_view(dispatcher, 0);
    view_dispatcher_free(dispatcher);
    text_input_free(text_input);

    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    if(!ctx.submitted) return false;

    char safe_name[32];
    uhf_sanitize_filename(out, safe_name, sizeof(safe_name));
    strncpy(out, safe_name, out_size - 1);
    out[out_size - 1] = '\0';
    return out[0] != '\0';
}

static bool uhf_save_index_epc_csv(UhfApp* app, const char* filename) {
    if(!app || !filename || !filename[0]) return false;

    char base_name[32];
    uhf_sanitize_filename(filename, base_name, sizeof(base_name));

    char file_name_with_ext[40];
    snprintf(file_name_with_ext, sizeof(file_name_with_ext), "%s.csv", base_name);

    Storage* storage = furi_record_open(RECORD_STORAGE);
    if(!storage) {
        uhf_set_status(app, "Storage unavailable");
        return false;
    }

    if(!storage_dir_exists(storage, UHF_APP_DATA_DIR)) {
        const FS_Error mkdir_result = storage_common_mkdir(storage, UHF_APP_DATA_DIR);
        if(mkdir_result != FSE_OK && mkdir_result != FSE_EXIST) {
            furi_record_close(RECORD_STORAGE);
            uhf_set_status(app, "Create dir failed");
            return false;
        }
    }

    char path[128];
    snprintf(path, sizeof(path), UHF_APP_DATA_DIR "/%s", file_name_with_ext);

    File* file = storage_file_alloc(storage);
    if(!file) {
        furi_record_close(RECORD_STORAGE);
        uhf_set_status(app, "File alloc failed");
        return false;
    }

    bool ok = false;
    do {
        if(!storage_file_open(file, path, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
            uhf_set_status(app, "Open file failed");
            break;
        }

        const char* header = "index,epc\n";
        if(storage_file_write(file, header, strlen(header)) != strlen(header)) {
            uhf_set_status(app, "Write header failed");
            break;
        }

        if(!uhf_data_lock(app, 50)) {
            uhf_set_status(app, "Busy");
            break;
        }

        size_t index = 1;
        char line[96];
        for(size_t i = 0; i < UHF_MAX_TAGS; i++) {
            if(!app->tags[i].used) continue;
            if(strncmp(app->tags[i].epc, "E2", 2) != 0) continue;

            const int len = snprintf(line, sizeof(line), "%lu,%s\n", (unsigned long)index, app->tags[i].epc);
            if(len <= 0 || (size_t)len >= sizeof(line)) continue;

            if(storage_file_write(file, line, (size_t)len) != (size_t)len) {
                uhf_data_unlock(app);
                uhf_set_status(app, "Write record failed");
                goto save_cleanup;
            }

            index++;
        }
        uhf_data_unlock(app);

        storage_file_sync(file);
        uhf_set_status(app, "Saved CSV: %s", file_name_with_ext);
        if(app->notifications) {
            notification_message(app->notifications, &sequence_success);
        }
        ok = true;
    } while(false);

save_cleanup:
    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
    return ok;
}

static size_t uhf_count_e2_tags(UhfApp* app) {
    if(!app) return 0;
    if(!uhf_data_lock(app, 20)) return 0;

    size_t total = 0;
    for(size_t i = 0; i < UHF_MAX_TAGS; i++) {
        if(!app->tags[i].used) continue;
        if(strncmp(app->tags[i].epc, "E2", 2) != 0) continue;
        total++;
    }

    uhf_data_unlock(app);
    return total;
}

static void uhf_move_list_selection(UhfApp* app, bool down) {
    if(!app) return;

    const size_t total = uhf_count_e2_tags(app);
    if(total == 0) {
        app->list_selected_index = 0;
        app->list_top_index = 0;
        uhf_set_status(app, "No tags yet");
        return;
    }

    if(app->list_selected_index >= total) {
        app->list_selected_index = total - 1U;
    }

    const size_t page_size = UHF_LIST_VISIBLE_ROWS;
    const size_t page_count = (total + page_size - 1U) / page_size;
    const size_t max_top = (total > page_size) ? (total - page_size) : 0U;
    size_t top = app->list_top_index;
    if(top > max_top) {
        top = max_top;
    }

    if(down) {
        if(top < max_top) {
            const size_t next_top = top + page_size;
            top = (next_top > max_top) ? max_top : next_top;
        }
    } else {
        if(top > page_size) {
            top -= page_size;
        } else {
            top = 0U;
        }
    }

    app->list_top_index = top;
    app->list_selected_index = top;

    const size_t current_page = (top / page_size) + 1U;

    uhf_set_status(
        app,
        "Page %lu/%lu",
        (unsigned long)current_page,
        (unsigned long)page_count);
}

static void uhf_toggle_inventory_with_cooldown(UhfApp* app) {
    if(!app) return;

    const uint32_t now = furi_get_tick();
    if((now - app->last_inv_cmd_tick) < UHF_INV_CMD_COOLDOWN_MS) {
        uhf_set_status(app, "Inventory cooldown");
        return;
    }
    app->last_inv_cmd_tick = now;

    if(app->inventory_running) {
        uhf_stop_inventory(app);
        uhf_set_status(app, "Inventory stopped");
    } else {
        uhf_start_inventory(app);
    }
}

static void uhf_enter_about_page(UhfApp* app) {
    if(!app) return;

    app->about_return_page = app->page;
    app->about_top_line = 0;
    app->page = UhfPageAbout;
    uhf_set_status(app, "About");
}

static void uhf_exit_about_page(UhfApp* app) {
    if(!app) return;

    if(app->about_return_page == UhfPageAbout) {
        app->about_return_page = UhfPageCounter;
    }
    app->page = app->about_return_page;
}

static void uhf_about_scroll(UhfApp* app, bool down) {
    if(!app || app->page != UhfPageAbout) return;

    const size_t total_lines = COUNT_OF(uhf_about_lines);
    if(total_lines <= UHF_ABOUT_VISIBLE_LINES) {
        app->about_top_line = 0;
        return;
    }

    const size_t max_top = total_lines - UHF_ABOUT_VISIBLE_LINES;
    size_t top = app->about_top_line;
    const size_t page_step = UHF_ABOUT_VISIBLE_LINES;

    if(down) {
        if(top < max_top) {
            const size_t next_top = top + page_step;
            top = (next_top > max_top) ? max_top : next_top;
        }
    } else {
        if(top > page_step) {
            top -= page_step;
        } else {
            top = 0U;
        }
    }

    app->about_top_line = top;
}

static void uhf_list_menu_execute(UhfApp* app, uint32_t item) {
    if(!app) return;

    switch(item) {
    case UhfListMenuItemSave:
        if(uhf_prompt_csv_filename(app, app->csv_filename, sizeof(app->csv_filename))) {
            (void)uhf_save_index_epc_csv(app, app->csv_filename);
        } else {
            uhf_set_status(app, "Save canceled");
        }
        break;
    case UhfListMenuItemAbout:
        uhf_enter_about_page(app);
        break;
    default:
        break;
    }
}

static void uhf_list_menu_submenu_callback(void* context, uint32_t index) {
    UhfListMenuCtx* menu_ctx = context;
    if(!menu_ctx) return;

    menu_ctx->selected = index;
    menu_ctx->submitted = true;
    if(menu_ctx->dispatcher) {
        view_dispatcher_stop(menu_ctx->dispatcher);
    }
}

static bool uhf_list_menu_back_callback(void* context) {
    UhfListMenuCtx* menu_ctx = context;
    if(!menu_ctx) return true;

    menu_ctx->submitted = false;
    if(menu_ctx->dispatcher) {
        view_dispatcher_stop(menu_ctx->dispatcher);
    }
    return true;
}

static void uhf_show_list_menu(UhfApp* app) {
    if(!app || !app->gui || !app->view_port) return;

    Submenu* submenu = submenu_alloc();
    ViewDispatcher* dispatcher = view_dispatcher_alloc();
    if(!submenu || !dispatcher) {
        if(submenu) submenu_free(submenu);
        if(dispatcher) view_dispatcher_free(dispatcher);
        return;
    }

    UhfListMenuCtx menu_ctx = {
        .dispatcher = dispatcher,
        .selected = UhfListMenuItemSave,
        .submitted = false,
    };

    submenu_set_header(submenu, "UHF Expansion");
    submenu_add_item(
        submenu,
        "Save",
        UhfListMenuItemSave,
        uhf_list_menu_submenu_callback,
        &menu_ctx);
    submenu_add_item(
        submenu,
        "About",
        UhfListMenuItemAbout,
        uhf_list_menu_submenu_callback,
        &menu_ctx);

    view_dispatcher_set_event_callback_context(dispatcher, &menu_ctx);
    view_dispatcher_set_navigation_event_callback(dispatcher, uhf_list_menu_back_callback);
    view_dispatcher_add_view(dispatcher, 0, submenu_get_view(submenu));

    gui_remove_view_port(app->gui, app->view_port);
    view_dispatcher_attach_to_gui(dispatcher, app->gui, ViewDispatcherTypeFullscreen);
    view_dispatcher_switch_to_view(dispatcher, 0);
    view_dispatcher_run(dispatcher);

    view_dispatcher_remove_view(dispatcher, 0);
    view_dispatcher_free(dispatcher);
    submenu_free(submenu);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    if(menu_ctx.submitted) {
        uhf_list_menu_execute(app, menu_ctx.selected);
    }
}

static void uhf_set_startup_text(UhfApp* app, const char* text, const char* subtext, uint8_t dots) {
    if(!app) return;

    strncpy(app->startup_text, text ? text : "", sizeof(app->startup_text) - 1);
    app->startup_text[sizeof(app->startup_text) - 1] = '\0';

    strncpy(app->startup_subtext, subtext ? subtext : "", sizeof(app->startup_subtext) - 1);
    app->startup_subtext[sizeof(app->startup_subtext) - 1] = '\0';

    app->startup_dots = dots;
    if(app->view_port) {
        view_port_update(app->view_port);
    }
}

static void uhf_run_startup_sequence(UhfApp* app) {
    if(!app) return;

    app->startup_active = true;
    for(uint8_t i = 0; i < 6; i++) {
        uhf_set_startup_text(app, "Loading", "Preparing UHF Expansion", (uint8_t)(i % 4U));
        furi_delay_ms(100);
    }

    bool requested = false;
    bool got_version = false;
    for(uint8_t i = 0; i < 12; i++) {
        uhf_set_startup_text(app, "Getting version", "Checking module", (uint8_t)(i % 4U));

        if(!requested) {
            uhf_request_version(app);
            requested = true;
        }

        uhf_process_rx(app);
        if(uhf_has_version(app)) {
            got_version = true;
            break;
        }
        furi_delay_ms(80);
    }

    if(got_version) {
        char line[40];
        snprintf(line, sizeof(line), "Version %s", app->version);
        uhf_set_startup_text(app, "Ready", line, 0);
        uhf_set_status(app, "Ready");
        furi_delay_ms(650);
    } else {
        uhf_set_startup_text(app, "Version not found", "Please replug module", 0);
        uhf_set_status(app, "No version, replug module");
        furi_delay_ms(900);
    }

    app->startup_active = false;
    if(app->view_port) {
        view_port_update(app->view_port);
    }
}

static bool uhf_has_version(UhfApp* app) {
    bool has = false;
    if(uhf_data_lock(app, 10)) {
        has = app->version[0] != '\0';
        uhf_data_unlock(app);
    }
    return has;
}

static void uhf_clear_version(UhfApp* app) {
    if(uhf_data_lock(app, 10)) {
        app->version[0] = '\0';
        uhf_data_unlock(app);
    }
}

static uint32_t uhf_read_be(const uint8_t* data, size_t len) {
    uint32_t value = 0;
    for(size_t i = 0; i < len; i++) {
        value = (value << 8) | data[i];
    }
    return value;
}

static bool uhf_bytes_to_hex(const uint8_t* data, size_t len, char* out, size_t out_size) {
    if(out_size < (len * 2 + 1)) return false;

    for(size_t i = 0; i < len; i++) {
        snprintf(&out[i * 2], 3, "%02X", data[i]);
    }
    out[len * 2] = '\0';
    return true;
}

static UhfTagEntry* uhf_find_or_add_tag(UhfApp* app, const char* epc_hex, bool* is_new_tag) {
    for(size_t i = 0; i < UHF_MAX_TAGS; i++) {
        if(app->tags[i].used && strcmp(app->tags[i].epc, epc_hex) == 0) {
            if(is_new_tag) *is_new_tag = false;
            return &app->tags[i];
        }
    }

    for(size_t i = 0; i < UHF_MAX_TAGS; i++) {
        if(!app->tags[i].used) {
            app->tags[i].read_count = 0;
            app->tags[i].rssi = 0;
            app->tags[i].frequency = 0;
            app->tags[i].antenna = 0;
            strncpy(app->tags[i].epc, epc_hex, sizeof(app->tags[i].epc) - 1);
            app->tags[i].epc[sizeof(app->tags[i].epc) - 1] = '\0';
            app->tags[i].used = true;
            app->tag_count++;
            if(is_new_tag) *is_new_tag = true;
            return &app->tags[i];
        }
    }

    return NULL;
}

static bool uhf_build_frame(
    uint8_t cmd,
    const uint8_t* payload,
    size_t payload_len,
    uint8_t* out,
    size_t out_size,
    size_t* frame_size) {
    const size_t len_field = payload_len + 3U;
    const size_t total_size = len_field + 2U;
    if(total_size > out_size || len_field > UINT8_MAX) return false;

    out[0] = UHF_FRAME_START;
    out[1] = (uint8_t)len_field;
    out[2] = UHF_DEFAULT_ADDR;
    out[3] = cmd;
    if(payload_len) {
        memcpy(&out[4], payload, payload_len);
    }

    uint32_t checksum_acc = 0;
    for(size_t i = 0; i < total_size - 1U; i++) {
        checksum_acc = (checksum_acc + out[i]) & 0xFFU;
    }
    out[total_size - 1U] = (uint8_t)((~checksum_acc + 1U) & 0xFFU);

    *frame_size = total_size;
    return true;
}

static bool uhf_send_raw_frame(UhfApp* app, const uint8_t* frame, size_t frame_size) {
    if(!frame || frame_size < 5U) return false;
    if(!app->serial && !app->soft_uart_enabled) return false;

    if(app->soft_uart_enabled) {
        uhf_soft_uart_tx(app, frame, frame_size);
    } else {
        furi_hal_serial_tx(app->serial, frame, frame_size);
        furi_hal_serial_tx_wait_complete(app->serial);
    }

    char hex[49] = "";
    const size_t shown = frame_size > 24U ? 24U : frame_size;
    if(uhf_bytes_to_hex(frame, shown, hex, sizeof(hex))) {
        uhf_diag_log(app, "TX len=%lu %s", (unsigned long)frame_size, hex);
    }

    return true;
}

static void uhf_store_last_rx_hex(UhfApp* app, const uint8_t* frame, size_t frame_size) {
    const size_t shown = frame_size > 20U ? 20U : frame_size;
    (void)uhf_bytes_to_hex(frame, shown, app->last_rx_hex, sizeof(app->last_rx_hex));
}

static bool uhf_send_command(UhfApp* app, uint8_t cmd, const uint8_t* payload, size_t payload_len) {
    uint8_t frame[272];
    size_t frame_size = 0;
    if(!uhf_build_frame(cmd, payload, payload_len, frame, sizeof(frame), &frame_size)) {
        return false;
    }

    return uhf_send_raw_frame(app, frame, frame_size);
}

static bool uhf_ensure_hardware(UhfApp* app) {
    if(app->hardware_ready) return true;

    uhf_force_direct_a6_a4(app);
    if(!app->serial) {
        uhf_set_status(app, "UART 13/14 open failed");
        return false;
    }

    app->hardware_ready = true;

    bool probe_ok = uhf_probe_current_serial(app, UHF_BAUD_RATE_LOW);
    if(!probe_ok && app->serial) {
        const FuriHalSerialId current_id = app->serial_id;
        const FuriHalSerialId other_id =
            (current_id == FuriHalSerialIdUsart) ? FuriHalSerialIdLpuart : FuriHalSerialIdUsart;

        uhf_diag_log(app, "Probe fail on %u, try %u", (unsigned)current_id, (unsigned)other_id);
        uhf_close_serial(app);
        if(uhf_open_serial(app, other_id)) {
            probe_ok = uhf_probe_current_serial(app, UHF_BAUD_RATE_LOW);
        }
    }

    if(!probe_ok && !app->serial) {
        if(!uhf_open_bridge_uart(app)) {
            app->hardware_ready = false;
            uhf_set_status(app, "UART reopen failed");
            return false;
        }
        app->baud_rate = UHF_BAUD_RATE_LOW;
        furi_hal_serial_set_br(app->serial, app->baud_rate);
    }

    if(probe_ok && uhf_has_version(app)) {
        uhf_set_status(app, "UART%d/%d V:%s", app->tx_ext_pin, app->rx_ext_pin, app->version);
    } else {
        uhf_set_status(app, "UART%d/%d ready (no ver)", app->tx_ext_pin, app->rx_ext_pin);
    }

    uhf_diag_log(
        app,
        "HW ready TX:%d RX:%d probe=%s",
        app->tx_ext_pin,
        app->rx_ext_pin,
        probe_ok ? "ok" : "fail");
    return true;
}

static void uhf_apply_baud(UhfApp* app, uint32_t baud_rate) {
    if(app->soft_uart_enabled) {
        app->baud_rate = UHF_BAUD_RATE_LOW;
        uhf_set_status(app, "Soft UART fixed 9600");
        return;
    }

    app->baud_rate = baud_rate;
    if(!app->serial) return;

    if(app->inventory_running) {
        app->inventory_running = false;
        (void)uhf_send_command(app, UHF_CMD_STOP_INV, NULL, 0);
    }

    furi_hal_serial_async_rx_stop(app->serial);
    furi_hal_serial_set_br(app->serial, baud_rate);
    furi_hal_serial_async_rx_start(app->serial, uhf_on_rx_irq, app, true);

    app->frame_buffer_len = 0;
    if(app->rx_stream) {
        (void)furi_stream_buffer_reset(app->rx_stream);
    }
    uhf_set_status(app, "Baud: %lu", (unsigned long)baud_rate);
}

static void __attribute__((unused)) uhf_toggle_baud(UhfApp* app) {
    if(!uhf_ensure_hardware(app)) return;
    uhf_apply_baud(app, UHF_BAUD_RATE_LOW);
    uhf_set_status(app, "Baud fixed: 9600");
}

static void uhf_stop_inventory(UhfApp* app) {
    static const uint8_t stop_frame[] = {0xA0, 0x03, 0x00, 0x8C, 0xD1};
    app->inventory_running = false;
    if(app->hardware_ready) {
        (void)uhf_send_raw_frame(app, stop_frame, sizeof(stop_frame));
    }
}

static void uhf_start_inventory(UhfApp* app) {
    static const uint8_t start_frame[] = {0xA0, 0x04, 0x00, 0x89, 0x01, 0xD2};
    if(!uhf_ensure_hardware(app)) return;
    (void)furi_stream_buffer_reset(app->rx_stream);
    app->frame_buffer_len = 0;
    const bool sent = uhf_send_raw_frame(app, start_frame, sizeof(start_frame));
    uhf_process_rx(app);

    if(sent) {
        app->inventory_running = true;
        uhf_set_status(app, "Inventory running");
    } else {
        uhf_set_status(app, "Start inventory failed");
    }
}

static void uhf_request_version(UhfApp* app) {
    if(!uhf_ensure_hardware(app)) return;
    app->frame_buffer_len = 0;
    app->rx_bytes = 0;
    app->rx_frames = 0;
    app->rx_errors = 0;
    app->last_rx_hex[0] = '\0';
    uhf_clear_version(app);
    if(app->rx_stream) {
        (void)furi_stream_buffer_reset(app->rx_stream);
    }

    static const uint8_t version_frame[] = {0xA0, 0x03, 0x00, 0x72, 0xEB};
    bool sent = false;
    for(size_t attempt = 0; attempt < 2; attempt++) {
        if(uhf_send_raw_frame(app, version_frame, sizeof(version_frame))) {
            sent = true;
        }
        uhf_process_rx(app);
        furi_delay_ms(8);
    }

    if(sent) {
        uhf_set_status(app, "Version checking...");
        uhf_diag_log(app, "Version req TX:%d RX:%d", app->tx_ext_pin, app->rx_ext_pin);
    } else {
        uhf_set_status(app, "Version tx failed");
        uhf_diag_log(app, "Version tx failed");
    }
}

static void __attribute__((unused)) uhf_swap_soft_uart_direction(UhfApp* app) {
    if(!uhf_ensure_hardware(app)) return;
    uhf_force_direct_a6_a4(app);
    uhf_set_status(app, "UART bridge reset");
}

static bool uhf_add_inventory_tag(
    UhfApp* app,
    const uint8_t* epc,
    size_t epc_len,
    uint8_t antenna,
    uint32_t rssi,
    uint32_t frequency) {
    if(epc_len == 0 || epc_len > (UHF_EPC_HEX_MAX / 2U)) return false;
    if(epc[0] != 0xE2U) return false;

    char epc_hex[UHF_EPC_HEX_MAX + 1];
    if(!uhf_bytes_to_hex(epc, epc_len, epc_hex, sizeof(epc_hex))) return false;

    bool is_new_tag = false;
    if(!uhf_data_lock(app, 10)) return false;

    UhfTagEntry* tag = uhf_find_or_add_tag(app, epc_hex, &is_new_tag);
    if(!tag) {
        uhf_data_unlock(app);
        uhf_set_status(app, "Tag cache full");
        return false;
    }

    tag->read_count++;
    tag->last_seen = furi_get_tick();
    tag->antenna = antenna;
    tag->rssi = rssi;
    tag->frequency = frequency;
    uhf_data_unlock(app);

    uhf_notify_tag_found(app);

    if(is_new_tag) {
        const size_t total = uhf_count_e2_tags(app);
        if(total > UHF_LIST_VISIBLE_ROWS) {
            app->list_top_index = total - UHF_LIST_VISIBLE_ROWS;
        } else {
            app->list_top_index = 0;
        }
        app->list_selected_index = total ? (total - 1U) : 0;
        uhf_set_status(app, "Tag Found: %lu", (unsigned long)total);
    }

    return true;
}

static bool uhf_parse_pc_epc_at(UhfApp* app, const uint8_t* data, size_t data_len, size_t pc_offset, uint8_t antenna) {
    if(data_len < pc_offset + 4U) return false;

    const uint16_t pc = (uint16_t)((data[pc_offset] << 8) | data[pc_offset + 1U]);
    const size_t epc_words = (pc >> 11) & 0x1F;
    const size_t epc_len = epc_words * 2U;
    const size_t epc_offset = pc_offset + 2U;
    const size_t meta_offset = epc_offset + epc_len;

    if(epc_len == 0 || epc_len > (UHF_EPC_HEX_MAX / 2U) || data_len < meta_offset) return false;

    uint32_t rssi = 0;
    uint32_t frequency = 0;
    if(data_len >= meta_offset + 7U) {
        rssi = uhf_read_be(&data[meta_offset], 4);
        frequency = uhf_read_be(&data[meta_offset + 4U], 3);
    }

    return uhf_add_inventory_tag(app, &data[epc_offset], epc_len, antenna, rssi, frequency);
}

static bool uhf_parse_inventory_buffer_frame(UhfApp* app, const uint8_t* data, size_t data_len) {
    if(data_len < 11U) return false;

    const size_t inv_data_len = data[0];
    const size_t required_len = 1U + inv_data_len + 4U + 3U + 1U + 1U;
    if(inv_data_len < 4U || data_len < required_len) return false;

    const uint8_t* inv_data = &data[1];
    const size_t epc_len = inv_data_len - 4U;
    const size_t offset = 1U + inv_data_len;
    const uint8_t antenna = data[offset + 7U];
    const uint32_t rssi = uhf_read_be(&data[offset], 4);
    const uint32_t frequency = uhf_read_be(&data[offset + 4U], 3);

    return uhf_add_inventory_tag(app, &inv_data[2], epc_len, antenna, rssi, frequency);
}

static bool uhf_parse_inventory_frame(UhfApp* app, const uint8_t* data, size_t data_len, uint8_t cmd) {
    UNUSED(cmd);

    if(uhf_parse_pc_epc_at(app, data, data_len, 1U, data_len ? data[0] : 0U)) return true;
    if(uhf_parse_inventory_buffer_frame(app, data, data_len)) return true;

    for(size_t offset = 0; offset < 3U && offset < data_len; offset++) {
        if(uhf_parse_pc_epc_at(app, data, data_len, offset, 0)) return true;
    }

    // Fallback for modules that return non-standard layouts: capture first E2-prefixed EPC-like payload.
    static const uint8_t lengths[] = {12U, 16U, 24U, 8U};
    for(size_t i = 0; i < data_len; i++) {
        if(data[i] != 0xE2U) continue;
        for(size_t l = 0; l < sizeof(lengths); l++) {
            const size_t epc_len = lengths[l];
            if(i + epc_len <= data_len) {
                if(uhf_add_inventory_tag(app, &data[i], epc_len, 0, 0, 0)) {
                    return true;
                }
            }
        }
    }

    return false;
}

static void uhf_handle_frame(UhfApp* app, const uint8_t* frame, size_t frame_size) {
    if(frame_size < 5U || frame[0] != UHF_FRAME_START) return;

    uhf_store_last_rx_hex(app, frame, frame_size);

    uint8_t checksum_acc = 0;
    for(size_t i = 0; i < frame_size; i++) {
        checksum_acc = (uint8_t)(checksum_acc + frame[i]);
    }
    if(checksum_acc != 0U) {
        app->rx_errors++;
    }

    app->rx_frames++;

    const uint8_t cmd = frame[3];
    const size_t data_len = (frame[1] >= 3U) ? (size_t)(frame[1] - 3U) : 0U;
    const uint8_t* data = &frame[4];

    uhf_diag_log(
        app,
        "RX cmd=%02X len=%lu cs=%s",
        cmd,
        (unsigned long)data_len,
        (checksum_acc == 0U) ? "ok" : "bad");

    if(cmd == UHF_CMD_GET_VERSION && data_len >= 3U) {
        if(uhf_data_lock(app, 10)) {
            snprintf(app->version, sizeof(app->version), "%u.%u.%u", data[0], data[1], data[2]);
            uhf_data_unlock(app);
        }
        uhf_set_status(app, "Version %s", app->version);
        uhf_diag_log(app, "Version=%s", app->version);
    } else if(cmd == UHF_CMD_START_INV || cmd == UHF_CMD_INV_ALT || app->inventory_running) {
        (void)uhf_parse_inventory_frame(app, data, data_len, cmd);
    } else if(cmd == UHF_CMD_STOP_INV) {
        if(!app->inventory_running) {
            uhf_set_status(app, "Inventory stopped");
        }
    }
}

static void uhf_process_rx(UhfApp* app) {
    uint8_t chunk[64];
    size_t got = 0;
    size_t chunk_budget = UHF_RX_CHUNKS_PER_PASS;
    size_t frame_budget = UHF_RX_FRAMES_PER_PASS;

    while(chunk_budget && frame_budget &&
          (got = furi_stream_buffer_receive(app->rx_stream, chunk, sizeof(chunk), 0)) > 0U) {
        chunk_budget--;
        app->rx_bytes += got;
        if(app->frame_buffer_len + got > sizeof(app->frame_buffer)) {
            app->rx_errors++;
            app->frame_buffer_len = 0;
        }

        memcpy(&app->frame_buffer[app->frame_buffer_len], chunk, got);
        app->frame_buffer_len += got;

        size_t index = 0;
        while(index < app->frame_buffer_len) {
            while(index < app->frame_buffer_len && app->frame_buffer[index] != UHF_FRAME_START) {
                index++;
            }
            if((app->frame_buffer_len - index) < 2U) break;

            const size_t frame_size = (size_t)app->frame_buffer[index + 1U] + 2U;
            if(frame_size < 5U) {
                app->rx_errors++;
                index++;
                continue;
            }
            if((app->frame_buffer_len - index) < frame_size) break;

            uhf_handle_frame(app, &app->frame_buffer[index], frame_size);
            index += frame_size;

            frame_budget--;
            if(frame_budget == 0U) {
                break;
            }
        }

        if(index > 0U) {
            const size_t remain = app->frame_buffer_len - index;
            if(remain) {
                memmove(app->frame_buffer, &app->frame_buffer[index], remain);
            }
            app->frame_buffer_len = remain;
        }

        if(frame_budget == 0U) {
            break;
        }
    }

    if(app->soft_uart_enabled) {
        uint8_t b = 0;
        size_t soft_read = 0;
        while(frame_budget && soft_read < UHF_SOFT_UART_RX_BATCH &&
              uhf_soft_uart_rx_byte(app, &b, UHF_SOFT_UART_FRAME_WAIT_US)) {
            if(app->frame_buffer_len >= sizeof(app->frame_buffer)) {
                app->rx_errors++;
                app->frame_buffer_len = 0;
            }
            app->frame_buffer[app->frame_buffer_len++] = b;
            app->rx_bytes++;
            soft_read++;

            size_t index = 0;
            while(index < app->frame_buffer_len) {
                while(index < app->frame_buffer_len && app->frame_buffer[index] != UHF_FRAME_START) {
                    index++;
                }
                if((app->frame_buffer_len - index) < 2U) break;

                const size_t frame_size = (size_t)app->frame_buffer[index + 1U] + 2U;
                if(frame_size < 5U) {
                    app->rx_errors++;
                    index++;
                    continue;
                }
                if((app->frame_buffer_len - index) < frame_size) break;

                uhf_handle_frame(app, &app->frame_buffer[index], frame_size);
                index += frame_size;

                frame_budget--;
                if(frame_budget == 0U) {
                    break;
                }
            }

            if(index > 0U) {
                const size_t remain = app->frame_buffer_len - index;
                if(remain) {
                    memmove(app->frame_buffer, &app->frame_buffer[index], remain);
                }
                app->frame_buffer_len = remain;
            }
        }
    }
}

static bool uhf_wait_for_version(UhfApp* app, uint32_t timeout_ms) {
    const uint32_t started = furi_get_tick();
    while((furi_get_tick() - started) < timeout_ms) {
        uhf_process_rx(app);
        if(uhf_has_version(app)) {
            return true;
        }
        furi_delay_ms(app->soft_uart_enabled ? 1U : 12U);
    }
    return false;
}

static bool uhf_probe_current_serial(UhfApp* app, uint32_t baud) {
    if(!app->serial && !app->soft_uart_enabled) return false;

    uhf_apply_baud(app, baud);
    uhf_clear_version(app);
    if(!uhf_has_version(app)) {
        uhf_request_version(app);
    }
    return uhf_wait_for_version(app, UHF_PROBE_TIMEOUT_MS);
}

static bool __attribute__((unused)) uhf_is_target_uart_pair(int8_t tx_pin, int8_t rx_pin) {
    const int8_t a6 = uhf_target_pin_a6();
    const int8_t a4 = uhf_target_pin_a4();
    return ((tx_pin == a6) && (rx_pin == a4)) || ((tx_pin == a4) && (rx_pin == a6));
}

static bool __attribute__((unused)) uhf_save_records(UhfApp* app) {
    if(!uhf_data_lock(app, 50)) {
        uhf_set_status(app, "Busy");
        return false;
    }

    if(app->tag_count == 0U) {
        uhf_data_unlock(app);
        uhf_set_status(app, "No records to save");
        return false;
    }

    Storage* storage = furi_record_open(RECORD_STORAGE);
    if(!storage) {
        uhf_data_unlock(app);
        uhf_set_status(app, "Storage unavailable");
        return false;
    }

    if(!storage_dir_exists(storage, UHF_APP_DATA_DIR)) {
        const FS_Error mkdir_result = storage_common_mkdir(storage, UHF_APP_DATA_DIR);
        if(mkdir_result != FSE_OK && mkdir_result != FSE_EXIST) {
            furi_record_close(RECORD_STORAGE);
            uhf_data_unlock(app);
            uhf_set_status(app, "Create dir failed");
            return false;
        }
    }

    char path[128];
    const uint32_t now = furi_get_tick();
    snprintf(path, sizeof(path), UHF_APP_DATA_DIR "/tags_%lu.csv", (unsigned long)now);

    File* file = storage_file_alloc(storage);
    if(!file) {
        furi_record_close(RECORD_STORAGE);
        uhf_data_unlock(app);
        uhf_set_status(app, "File alloc failed");
        return false;
    }

    bool ok = false;

    do {
        if(!storage_file_open(file, path, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
            uhf_set_status(app, "Open file failed");
            break;
        }

        const char* header = "EPC,RSSI,Frequency,Antenna,ReadCount,LastSeenTick\n";
        if(storage_file_write(file, header, strlen(header)) != strlen(header)) {
            uhf_set_status(app, "Write header failed");
            break;
        }

        char line[192];
        for(size_t i = 0; i < UHF_MAX_TAGS; i++) {
            if(!app->tags[i].used) continue;

            const int len = snprintf(
                line,
                sizeof(line),
                "%s,%lu,%lu,%u,%u,%lu\n",
                app->tags[i].epc,
                (unsigned long)app->tags[i].rssi,
                (unsigned long)app->tags[i].frequency,
                app->tags[i].antenna,
                app->tags[i].read_count,
                (unsigned long)app->tags[i].last_seen);
            if(len <= 0 || (size_t)len >= sizeof(line)) continue;

            if(storage_file_write(file, line, (size_t)len) != (size_t)len) {
                uhf_set_status(app, "Write record failed");
                break;
            }
        }

        storage_file_sync(file);
        uhf_set_status(app, "Saved: %s", path);
        ok = true;
    } while(false);

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
    uhf_data_unlock(app);
    return ok;
}

static bool uhf_save_diag_log(UhfApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    if(!storage) {
        uhf_set_status(app, "Storage unavailable");
        return false;
    }

    if(!storage_dir_exists(storage, UHF_DIAG_DATA_DIR)) {
        const FS_Error mkdir_result = storage_common_mkdir(storage, UHF_DIAG_DATA_DIR);
        if(mkdir_result != FSE_OK && mkdir_result != FSE_EXIST) {
            furi_record_close(RECORD_STORAGE);
            uhf_set_status(app, "Create dir failed");
            return false;
        }
    }

    char path[128];
    const uint32_t now = furi_get_tick();
    snprintf(path, sizeof(path), UHF_DIAG_DATA_DIR "/diag_%lu.log", (unsigned long)now);

    File* file = storage_file_alloc(storage);
    if(!file) {
        furi_record_close(RECORD_STORAGE);
        uhf_set_status(app, "File alloc failed");
        return false;
    }

    bool ok = false;
    do {
        if(!storage_file_open(file, path, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
            uhf_set_status(app, "Open log failed");
            break;
        }

        char header[128];
        const int header_len = snprintf(
            header,
            sizeof(header),
            "diag tick=%lu tx=%d rx=%d baud=%lu\\n",
            (unsigned long)now,
            app->tx_ext_pin,
            app->rx_ext_pin,
            (unsigned long)app->baud_rate);
        if(header_len > 0) {
            (void)storage_file_write(file, header, (size_t)header_len);
        }

        const size_t count = app->diag_count;
        const size_t start = (app->diag_head + UHF_DIAG_LOG_LINES - count) % UHF_DIAG_LOG_LINES;
        for(size_t i = 0; i < count; i++) {
            const size_t idx = (start + i) % UHF_DIAG_LOG_LINES;
            const char* line = app->diag_log[idx];
            if(!line[0]) continue;
            const size_t len = strlen(line);
            if(len) {
                (void)storage_file_write(file, line, len);
                (void)storage_file_write(file, "\\n", 1);
            }

            // Yield periodically to keep UI/task scheduler responsive on long writes.
            if((i & 0x07U) == 0x07U) {
                furi_delay_ms(1);
            }
        }

        storage_file_sync(file);
        uhf_set_status(app, "Diag saved: %s", path);
        ok = true;
    } while(false);

    storage_file_close(file);
    storage_file_free(file);
    furi_record_close(RECORD_STORAGE);
    return ok;
}

static void uhf_clear_tags(UhfApp* app) {
    if(uhf_data_lock(app, 10)) {
        memset(app->tags, 0, sizeof(app->tags));
        app->tag_count = 0;
        app->list_top_index = 0;
        app->list_selected_index = 0;
        uhf_data_unlock(app);
    }
    uhf_set_status(app, "Records cleared");
}

static size_t uhf_collect_tag_previews(
    UhfApp* app,
    size_t start,
    UhfTagPreview* out,
    size_t max_items,
    size_t* total) {
    if(!app || !out || !max_items || !total) return 0;
    if(!uhf_data_lock(app, 20)) return 0;

    size_t copied = 0;
    size_t index = 0;
    size_t used_total = 0;

    for(size_t i = 0; i < UHF_MAX_TAGS; i++) {
        if(!app->tags[i].used) continue;
        if(strncmp(app->tags[i].epc, "E2", 2) != 0) continue;

        if(index >= start && copied < max_items) {
            strncpy(out[copied].epc, app->tags[i].epc, sizeof(out[copied].epc) - 1);
            out[copied].epc[sizeof(out[copied].epc) - 1] = '\0';
            out[copied].count = app->tags[i].read_count;
            copied++;
        }

        index++;
        used_total++;
    }

    *total = used_total;
    uhf_data_unlock(app);
    return copied;
}

static void uhf_draw_centered_text(Canvas* canvas, int y, const char* text) {
    if(!canvas || !text) return;

    const int width = canvas_string_width(canvas, text);
    int x = (128 - width) / 2;
    if(x < 0) x = 0;
    canvas_draw_str(canvas, x, y, text);
}

static void uhf_input_callback(InputEvent* event, void* context) {
    if(!context || !event) return;
    UhfApp* app = context;
    UhfEvent app_event = {.input = *event};
    if(app->event_queue) {
        furi_message_queue_put(app->event_queue, &app_event, 0);
    }
}

static void uhf_draw_callback(Canvas* canvas, void* context) {
    if(!context) return;
    UhfApp* app = context;

    char status[64] = "";
    char version[24] = "";
    size_t tag_count = app->tag_count;
    UhfPage page = app->page;
    size_t list_top = app->list_top_index;

    strncpy(status, app->status, sizeof(status) - 1);
    status[sizeof(status) - 1] = '\0';
    strncpy(version, app->version, sizeof(version) - 1);
    version[sizeof(version) - 1] = '\0';

    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);

    if(page == UhfPageAbout) {
        uhf_draw_centered_text(canvas, 11, "About UHF Expansion");
    } else {
        uhf_draw_centered_text(canvas, 11, "UHF Expansion");
    }

    if(app->startup_active) {
        char dots[5] = "";
        const uint8_t count = app->startup_dots > 3U ? 3U : app->startup_dots;
        for(uint8_t i = 0; i < count; i++) dots[i] = '.';
        dots[count] = '\0';

        char line[40];
        snprintf(line, sizeof(line), "%s%s", app->startup_text, dots);

        canvas_set_font(canvas, FontPrimary);
        uhf_draw_centered_text(canvas, 32, line);
        canvas_set_font(canvas, FontSecondary);
        if(app->startup_subtext[0]) {
            uhf_draw_centered_text(canvas, 48, app->startup_subtext);
        }
        return;
    }

    if(page == UhfPageAbout) {

        canvas_set_font(canvas, FontSecondary);
        const size_t total_lines = COUNT_OF(uhf_about_lines);
        size_t top = app->about_top_line;
        if(total_lines <= UHF_ABOUT_VISIBLE_LINES) {
            top = 0;
        } else {
            const size_t max_top = total_lines - UHF_ABOUT_VISIBLE_LINES;
            if(top > max_top) top = max_top;
        }

        int y = 24;
        for(size_t i = 0; i < UHF_ABOUT_VISIBLE_LINES; i++) {
            const size_t line_idx = top + i;
            if(line_idx >= total_lines) break;
            canvas_draw_str(canvas, 0, y, uhf_about_lines[line_idx]);
            y += 8;
        }
    } else if(page == UhfPageList) {
        UhfTagPreview previews[UHF_LIST_VISIBLE_ROWS];
        size_t total = 0;

        if(tag_count <= UHF_LIST_VISIBLE_ROWS) {
            list_top = 0;
        } else if(list_top + UHF_LIST_VISIBLE_ROWS > tag_count) {
            list_top = tag_count - UHF_LIST_VISIBLE_ROWS;
        }

        const size_t visible_count =
            uhf_collect_tag_previews(app, list_top, previews, COUNT_OF(previews), &total);

        if(total <= UHF_LIST_VISIBLE_ROWS) {
            list_top = 0;
        } else if(list_top + UHF_LIST_VISIBLE_ROWS > total) {
            list_top = total - UHF_LIST_VISIBLE_ROWS;
        }

        canvas_set_font(canvas, FontSecondary);
        char line[40];
        if(total == 0) {
            uhf_draw_centered_text(canvas, 36, "No tags yet");
        } else {
            int y = 22;
            const int epc_col_x = canvas_string_width(canvas, "000 ");
            const int epc_col_w = 127 - epc_col_x;
            for(size_t row = 0; row < visible_count; row++) {
                const size_t idx = list_top + row;
                if(idx >= total) break;

                char index_field[16];
                snprintf(index_field, sizeof(index_field), "%3lu ", (unsigned long)(idx + 1U));

                const char* epc = previews[row].epc;
                uhf_format_list_epc_compact(canvas, epc, epc_col_w, line, sizeof(line));

                canvas_draw_str(canvas, 0, y, index_field);
                canvas_draw_str(canvas, epc_col_x, y, line);
                y += 8;
            }
        }

        snprintf(line, sizeof(line), "%lu", (unsigned long)total);
        uhf_draw_right_text(canvas, 63, line);

        uhf_draw_scan_hint(canvas, app->inventory_running);
    } else {
        canvas_set_font(canvas, FontBigNumbers);
        char line[32];
        snprintf(line, sizeof(line), "%lu", (unsigned long)tag_count);
        uhf_draw_centered_text(canvas, 40, line);

        canvas_set_font(canvas, FontSecondary);
        const char* found_label = (tag_count == 1U) ? "Tag Found" : "Tags Found";
        uhf_draw_centered_text(canvas, 52, found_label);
        uhf_draw_scan_hint(canvas, app->inventory_running);
    }
}

static void __attribute__((unused))
    uhf_on_rx_irq(FuriHalSerialHandle* handle, FuriHalSerialRxEvent event, void* context) {
    UhfApp* app = context;
    if(!app || !app->rx_stream) return;

    if(event & FuriHalSerialRxEventData) {
        while(furi_hal_serial_async_rx_available(handle)) {
            const uint8_t b = furi_hal_serial_async_rx(handle);
            furi_stream_buffer_send(app->rx_stream, &b, 1, 0);
        }
    }
}

static bool uhf_open_serial(UhfApp* app, FuriHalSerialId serial_id) {
    FuriHalSerialHandle* serial = furi_hal_serial_control_acquire(serial_id);
    if(!serial) return false;

    furi_hal_serial_init(serial, app->baud_rate);
    furi_hal_serial_configure_framing(
        serial,
        FuriHalSerialDataBits8,
        FuriHalSerialParityNone,
        FuriHalSerialStopBits1);
    furi_hal_serial_enable_direction(serial, FuriHalSerialDirectionTx);
    furi_hal_serial_enable_direction(serial, FuriHalSerialDirectionRx);

    const GpioPin* tx_pin = furi_hal_serial_get_gpio_pin(serial, FuriHalSerialDirectionTx);
    const GpioPin* rx_pin = furi_hal_serial_get_gpio_pin(serial, FuriHalSerialDirectionRx);

    app->tx_ext_pin = tx_pin ? furi_hal_resources_get_ext_pin_number(tx_pin) : -1;
    app->rx_ext_pin = rx_pin ? furi_hal_resources_get_ext_pin_number(rx_pin) : -1;
    app->serial = serial;
    app->serial_id = serial_id;

    furi_hal_serial_async_rx_start(serial, uhf_on_rx_irq, app, true);
    return true;
}

static bool uhf_open_bridge_uart(UhfApp* app) {
    const FuriHalSerialId ids[] = {FuriHalSerialIdUsart, FuriHalSerialIdLpuart};
    FuriHalSerialId fallback_id = FuriHalSerialIdUsart;
    bool have_fallback = false;

    for(size_t i = 0; i < COUNT_OF(ids); i++) {
        if(!uhf_open_serial(app, ids[i])) continue;

        if(!have_fallback) {
            fallback_id = ids[i];
            have_fallback = true;
        }

        if((app->tx_ext_pin == UHF_BRIDGE_TX_EXT_PIN) && (app->rx_ext_pin == UHF_BRIDGE_RX_EXT_PIN)) {
            return true;
        }

        uhf_close_serial(app);
    }

    if(have_fallback) {
        return uhf_open_serial(app, fallback_id);
    }

    return false;
}

static void uhf_close_serial(UhfApp* app) {
    if(!app->serial) return;

    furi_hal_serial_async_rx_stop(app->serial);
    furi_hal_serial_disable_direction(app->serial, FuriHalSerialDirectionTx);
    furi_hal_serial_disable_direction(app->serial, FuriHalSerialDirectionRx);
    furi_hal_serial_deinit(app->serial);
    furi_hal_serial_control_release(app->serial);
    app->serial = NULL;
}

static bool __attribute__((unused)) uhf_pick_and_open_serial(UhfApp* app) {
    if(uhf_open_serial(app, FuriHalSerialIdUsart)) {
        const bool is_target_pins = uhf_is_target_uart_pair(app->tx_ext_pin, app->rx_ext_pin);
        if(is_target_pins) return true;

        // Keep USART as a usable fallback even if it is not A6/A4.
        return true;
    }

    if(uhf_open_serial(app, FuriHalSerialIdLpuart)) {
        return true;
    }

    app->tx_ext_pin = -1;
    app->rx_ext_pin = -1;
    return false;
}

static bool __attribute__((unused)) uhf_probe_reader_startup(UhfApp* app) {
    const uint32_t bauds[2] = {UHF_BAUD_RATE_LOW, UHF_BAUD_RATE_HIGH};
    char tx_label[12] = "N/A";
    char rx_label[12] = "N/A";

    if(!app->serial && !app->soft_uart_enabled && !uhf_pick_and_open_serial(app)) {
        return false;
    }

    for(size_t i = 0; i < 2; i++) {
        if(uhf_probe_current_serial(app, bauds[i])) {
            uhf_format_pin_label(app->tx_ext_pin, tx_label, sizeof(tx_label));
            uhf_format_pin_label(app->rx_ext_pin, rx_label, sizeof(rx_label));
            uhf_set_status(
                app,
                "Reader OK %lu TX:%s RX:%s",
                (unsigned long)app->baud_rate,
                tx_label,
                rx_label);
            return true;
        }
    }

    if(!app->soft_uart_enabled) {
        const FuriHalSerialId current_id = app->serial_id;
        const FuriHalSerialId other_id =
            (current_id == FuriHalSerialIdUsart) ? FuriHalSerialIdLpuart : FuriHalSerialIdUsart;

        uhf_close_serial(app);
        if(uhf_open_serial(app, other_id)) {
            for(size_t i = 0; i < 2; i++) {
                if(uhf_probe_current_serial(app, bauds[i])) {
                    uhf_format_pin_label(app->tx_ext_pin, tx_label, sizeof(tx_label));
                    uhf_format_pin_label(app->rx_ext_pin, rx_label, sizeof(rx_label));
                    uhf_set_status(
                        app,
                        "Reader OK %lu TX:%s RX:%s",
                        (unsigned long)app->baud_rate,
                        tx_label,
                        rx_label);
                    return true;
                }
            }
        }

        uhf_close_serial(app);
        (void)uhf_pick_and_open_serial(app);
        uhf_apply_baud(app, UHF_BAUD_RATE_LOW);
    }

    uhf_set_status(app, "No version. Check or swap A6/A4");
    return false;
}

static void uhf_toggle_serial_port(UhfApp* app) {
    if(!uhf_ensure_hardware(app)) return;

    // Keep LEFT-long as a deterministic recovery action: always re-apply fixed direct wiring.
    uhf_force_direct_a6_a4(app);
    uhf_set_status(app, "UART reset 9600");
}

static void uhf_toggle_page(UhfApp* app) {
    if(!app) return;

    if(app->page == UhfPageCounter) {
        const size_t total = uhf_count_e2_tags(app);
        app->page = UhfPageList;

        if(total > 0U) {
            app->list_selected_index = total - 1U;
        } else {
            app->list_selected_index = 0U;
        }

        if(total > UHF_LIST_VISIBLE_ROWS) {
            app->list_top_index = total - UHF_LIST_VISIBLE_ROWS;
        } else {
            app->list_top_index = 0;
        }

        uhf_set_status(app, "List page");
    } else {
        app->page = UhfPageCounter;
        uhf_set_status(app, "Counter page");
    }
}

static UhfApp* uhf_app_alloc(void) {
    UhfApp* app = malloc(sizeof(UhfApp));
    if(!app) return NULL;

    memset(app, 0, sizeof(UhfApp));

    app->tx_ext_pin = -1;
    app->rx_ext_pin = -1;
    app->serial_id = FuriHalSerialIdUsart;
    app->baud_rate = UHF_BAUD_RATE_LOW;
    uhf_set_status(app, "Init");

    app->data_mutex = furi_mutex_alloc(FuriMutexTypeRecursive);
    if(!app->data_mutex) {
        free(app);
        return NULL;
    }

    app->event_queue = furi_message_queue_alloc(16, sizeof(UhfEvent));
    app->rx_stream = furi_stream_buffer_alloc(UHF_RX_STREAM_SIZE, 1);
    if(!app->event_queue || !app->rx_stream) {
        uhf_app_free(app);
        return NULL;
    }

    app->gui = furi_record_open(RECORD_GUI);
    if(!app->gui) {
        uhf_app_free(app);
        return NULL;
    }

    app->notifications = furi_record_open(RECORD_NOTIFICATION);

    app->view_port = view_port_alloc();
    if(!app->view_port) {
        uhf_app_free(app);
        return NULL;
    }

    view_port_draw_callback_set(app->view_port, uhf_draw_callback, app);
    view_port_input_callback_set(app->view_port, uhf_input_callback, app);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    uhf_set_status(app, "OK Scan RList DClear UReset");

    return app;
}

static void uhf_app_free(UhfApp* app) {
    if(!app) return;

    if(app->hardware_ready && (app->serial || app->soft_uart_enabled)) {
        uhf_stop_inventory(app);
    }

    if(app->serial) {
        uhf_close_serial(app);
    }

    if(app->hardware_ready && app->otg_enabled_by_app && !app->otg_was_enabled) {
        if(app->power) {
            power_enable_otg(app->power, false);
        } else {
            furi_hal_power_disable_otg();
        }
    }

    if(app->hardware_ready && app->soft_uart_enabled) {
        furi_hal_gpio_init_simple(&gpio_ext_pa6, GpioModeAnalog);
        furi_hal_gpio_init_simple(&gpio_ext_pa4, GpioModeAnalog);
    }

    if(app->hardware_ready) {
        furi_hal_gpio_init_simple(&gpio_ext_pa7, GpioModeAnalog);
    }

    if(app->gui && app->view_port) {
        gui_remove_view_port(app->gui, app->view_port);
    }
    if(app->view_port) {
        view_port_free(app->view_port);
    }
    if(app->gui) {
        furi_record_close(RECORD_GUI);
    }
    if(app->notifications) {
        furi_record_close(RECORD_NOTIFICATION);
    }
    if(app->power) {
        furi_record_close(RECORD_POWER);
    }

    if(app->rx_stream) {
        furi_stream_buffer_free(app->rx_stream);
    }
    if(app->event_queue) {
        furi_message_queue_free(app->event_queue);
    }
    if(app->data_mutex) {
        furi_mutex_free(app->data_mutex);
    }
    free(app);
}

static void uhf_handle_input(UhfApp* app, const InputEvent* input) {
    if((input->key == InputKeyDown) && (input->type == InputTypeRelease)) {
        app->down_long_latched = false;
        return;
    }

    const bool fire = (input->type == InputTypeShort) || (input->type == InputTypeLong);
    if(!fire) return;

    app->key_count++;
    if(app->view_port) {
        view_port_update(app->view_port);
    }

    switch(input->key) {
    case InputKeyOk: {
        if(input->type == InputTypeLong) {
            if(app->page == UhfPageList || app->page == UhfPageCounter) {
                uhf_show_list_menu(app);
            }
            break;
        }

        if(input->type != InputTypeShort) {
            uhf_set_status(app, "Use short OK");
            break;
        }
        if(app->page == UhfPageAbout) {
            uhf_exit_about_page(app);
        } else {
            uhf_toggle_inventory_with_cooldown(app);
        }
        break;
    }
    case InputKeyLeft:
        if((app->page == UhfPageCounter || app->page == UhfPageList) &&
           input->type == InputTypeShort) {
            uhf_clear_tags(app);
        }
        break;
    case InputKeyUp:
        if(app->page == UhfPageAbout) {
            if(input->type == InputTypeShort) {
                uhf_about_scroll(app, false);
            }
        } else if(app->page == UhfPageList) {
            if(input->type == InputTypeShort) {
                uhf_move_list_selection(app, false);
            }
        } else {
            uhf_toggle_serial_port(app);
        }
        break;
    case InputKeyRight:
        if(app->page != UhfPageAbout) {
            uhf_toggle_page(app);
        }
        break;
    case InputKeyDown:
        if(app->page == UhfPageAbout) {
            if(input->type == InputTypeShort) {
                uhf_about_scroll(app, true);
            }
        } else if(app->page == UhfPageList) {
            if(input->type == InputTypeShort) {
                uhf_move_list_selection(app, true);
            }
        }
        break;
    case InputKeyBack:
        if(app->page == UhfPageAbout) {
            uhf_exit_about_page(app);
        } else {
            app->exit_requested = true;
        }
        break;
    default:
        break;
    }
}

int32_t uhf_expansion_app(void* p) {
    UNUSED(p);

    UhfApp* app = uhf_app_alloc();
    if(!app) return -1;

    uhf_run_startup_sequence(app);

    while(!app->exit_requested) {
        UhfEvent event;
        const uint32_t input_wait = (app->hardware_ready && app->soft_uart_enabled) ? 1U : 20U;
        if(furi_message_queue_get(app->event_queue, &event, input_wait) == FuriStatusOk) {
            uhf_handle_input(app, &event.input);
        }

        if(app->hardware_ready) {
            uhf_process_rx(app);
        }

        if(app->diag_save_pending) {
            app->diag_save_pending = false;
            app->diag_save_running = true;
            if(app->inventory_running) {
                uhf_stop_inventory(app);
                furi_delay_ms(2);
            }
            (void)uhf_save_diag_log(app);
            app->diag_save_running = false;
        }

        const uint32_t now = furi_get_tick();
        if(now - app->last_redraw_tick > 180U) {
            app->last_redraw_tick = now;
            view_port_update(app->view_port);
        }
    }

    uhf_app_free(app);
    return 0;
}
